const structureLabels = [
  'Largura do Nariz',
  'Altura do Nariz',
  'Comprimento do Nariz',
  'Ponte Nasal',
  'Ponta do Nariz',
  'Eixo da Ponte Nasal',
  'Altura da Sobrancelha',
  'Profundidade da Sobrancelha',
  'Altura da Bochecha',
  'Largura da Bochecha',
  'Comprimento da Bochecha',
  'Pálpebras',
  'Lábios',
  'Largura da Mandíbula',
  'Altura da Mandíbula',
  'Comprimento do Queixo',
  'Posição do Queixo',
  'Largura do Queixo',
  'Formato do Queixo',
  'Largura do Pescoço'
];