const maleHairs = [
    { drawable: 0, dlc: null },
    { drawable: 1, dlc: null },
    { drawable: 2, dlc: null },
    { drawable: 3, dlc: null },
    { drawable: 4, dlc: null },
    { drawable: 5, dlc: null },
    { drawable: 6, dlc: null },
    { drawable: 7, dlc: null },
    { drawable: 8, dlc: null },
    { drawable: 9, dlc: null },
    { drawable: 10, dlc: null },
    { drawable: 11, dlc: null },
    { drawable: 12, dlc: null },
    { drawable: 13, dlc: null },
    { drawable: 14, dlc: null },
    { drawable: 15, dlc: null },
    { drawable: 16, dlc: null },
    { drawable: 17, dlc: null },
    { drawable: 18, dlc: null },
    { drawable: 19, dlc: null },
    { drawable: 20, dlc: null },
    { drawable: 21, dlc: null },
    { drawable: 22, dlc: null },
    { drawable: 24, dlc: null },
    { drawable: 25, dlc: null },
    { drawable: 26, dlc: null },
    { drawable: 27, dlc: null },
    { drawable: 28, dlc: null },
    { drawable: 29, dlc: null },
    { drawable: 30, dlc: null },
    { drawable: 31, dlc: null },
    { drawable: 32, dlc: null },
    { drawable: 33, dlc: null },
    { drawable: 34, dlc: null },
    { drawable: 35, dlc: null },
    { drawable: 36, dlc: null },
    { drawable: 37, dlc: null },
    { drawable: 38, dlc: null },
    { drawable: 39, dlc: null },
    { drawable: 40, dlc: null },
    { drawable: 41, dlc: null },
    { drawable: 42, dlc: null },
    { drawable: 43, dlc: null },
    { drawable: 44, dlc: null },
    { drawable: 45, dlc: null },
    { drawable: 46, dlc: null },
    { drawable: 47, dlc: null },
    { drawable: 48, dlc: null },
    { drawable: 49, dlc: null },
    { drawable: 50, dlc: null },
    { drawable: 51, dlc: null },
    { drawable: 52, dlc: null },
    { drawable: 53, dlc: null },
    { drawable: 54, dlc: null },
    { drawable: 55, dlc: null },
    { drawable: 56, dlc: null },
    { drawable: 57, dlc: null },
    { drawable: 58, dlc: null },
    { drawable: 59, dlc: null },
    { drawable: 60, dlc: null },
    { drawable: 61, dlc: null },
    { drawable: 62, dlc: null },
    { drawable: 63, dlc: null },
    { drawable: 64, dlc: null },
    { drawable: 65, dlc: null },
    { drawable: 66, dlc: null },
    { drawable: 67, dlc: null },
    { drawable: 68, dlc: null },
    { drawable: 69, dlc: null },
    { drawable: 70, dlc: null },
    { drawable: 71, dlc: null },
    { drawable: 72, dlc: null },
    { drawable: 73, dlc: null },
    { drawable: 74, dlc: null },
    { drawable: 75, dlc: null },
    { drawable: 76, dlc: null },
    { drawable: 0, dlc: 'mp_m_sgv' },
    { drawable: 1, dlc: 'mp_m_sgv' },
    { drawable: 2, dlc: 'mp_m_sgv' },
    { drawable: 3, dlc: 'mp_m_sgv' },
    { drawable: 4, dlc: 'mp_m_sgv' },
    { drawable: 5, dlc: 'mp_m_sgv' },
    { drawable: 6, dlc: 'mp_m_sgv' },
    { drawable: 7, dlc: 'mp_m_sgv' },
    { drawable: 8, dlc: 'mp_m_sgv' },
    { drawable: 9, dlc: 'mp_m_sgv' },
    { drawable: 10, dlc: 'mp_m_sgv' },
    { drawable: 11, dlc: 'mp_m_sgv' },
    { drawable: 12, dlc: 'mp_m_sgv' },
    { drawable: 13, dlc: 'mp_m_sgv' },
    { drawable: 14, dlc: 'mp_m_sgv' },
    { drawable: 15, dlc: 'mp_m_sgv' },
    { drawable: 16, dlc: 'mp_m_sgv' },
    { drawable: 17, dlc: 'mp_m_sgv' },
    { drawable: 18, dlc: 'mp_m_sgv' },
    { drawable: 19, dlc: 'mp_m_sgv' },
    { drawable: 20, dlc: 'mp_m_sgv' },
    { drawable: 21, dlc: 'mp_m_sgv' },
    { drawable: 22, dlc: 'mp_m_sgv' },
    { drawable: 23, dlc: 'mp_m_sgv' },
    { drawable: 24, dlc: 'mp_m_sgv' },
    { drawable: 25, dlc: 'mp_m_sgv' },
    { drawable: 26, dlc: 'mp_m_sgv' },
    { drawable: 27, dlc: 'mp_m_sgv' },
    { drawable: 28, dlc: 'mp_m_sgv' },
    { drawable: 29, dlc: 'mp_m_sgv' },
    { drawable: 30, dlc: 'mp_m_sgv' },
    { drawable: 31, dlc: 'mp_m_sgv' },
    { drawable: 32, dlc: 'mp_m_sgv' },
    { drawable: 33, dlc: 'mp_m_sgv' },
    { drawable: 34, dlc: 'mp_m_sgv' },
    { drawable: 35, dlc: 'mp_m_sgv' },
    { drawable: 36, dlc: 'mp_m_sgv' },
];

const femaleHairs = [
    { drawable: 0, dlc: null },
    { drawable: 1, dlc: null },
    { drawable: 2, dlc: null },
    { drawable: 3, dlc: null },
    { drawable: 4, dlc: null },
    { drawable: 5, dlc: null },
    { drawable: 6, dlc: null },
    { drawable: 7, dlc: null },
    { drawable: 8, dlc: null },
    { drawable: 9, dlc: null },
    { drawable: 10, dlc: null },
    { drawable: 11, dlc: null },
    { drawable: 12, dlc: null },
    { drawable: 13, dlc: null },
    { drawable: 14, dlc: null },
    { drawable: 15, dlc: null },
    { drawable: 16, dlc: null },
    { drawable: 17, dlc: null },
    { drawable: 18, dlc: null },
    { drawable: 19, dlc: null },
    { drawable: 20, dlc: null },
    { drawable: 21, dlc: null },
    { drawable: 22, dlc: null },
    { drawable: 23, dlc: null },
    { drawable: 25, dlc: null },
    { drawable: 26, dlc: null },
    { drawable: 27, dlc: null },
    { drawable: 28, dlc: null },
    { drawable: 29, dlc: null },
    { drawable: 30, dlc: null },
    { drawable: 31, dlc: null },
    { drawable: 32, dlc: null },
    { drawable: 33, dlc: null },
    { drawable: 34, dlc: null },
    { drawable: 35, dlc: null },
    { drawable: 36, dlc: null },
    { drawable: 37, dlc: null },
    { drawable: 38, dlc: null },
    { drawable: 39, dlc: null },
    { drawable: 40, dlc: null },
    { drawable: 41, dlc: null },
    { drawable: 42, dlc: null },
    { drawable: 43, dlc: null },
    { drawable: 44, dlc: null },
    { drawable: 45, dlc: null },
    { drawable: 46, dlc: null },
    { drawable: 47, dlc: null },
    { drawable: 48, dlc: null },
    { drawable: 49, dlc: null },
    { drawable: 50, dlc: null },
    { drawable: 51, dlc: null },
    { drawable: 52, dlc: null },
    { drawable: 53, dlc: null },
    { drawable: 54, dlc: null },
    { drawable: 55, dlc: null },
    { drawable: 56, dlc: null },
    { drawable: 57, dlc: null },
    { drawable: 58, dlc: null },
    { drawable: 59, dlc: null },
    { drawable: 60, dlc: null },
    { drawable: 61, dlc: null },
    { drawable: 62, dlc: null },
    { drawable: 63, dlc: null },
    { drawable: 64, dlc: null },
    { drawable: 65, dlc: null },
    { drawable: 66, dlc: null },
    { drawable: 67, dlc: null },
    { drawable: 68, dlc: null },
    { drawable: 69, dlc: null },
    { drawable: 70, dlc: null },
    { drawable: 71, dlc: null },
    { drawable: 72, dlc: null },
    { drawable: 73, dlc: null },
    { drawable: 74, dlc: null },
    { drawable: 75, dlc: null },
    { drawable: 76, dlc: null },
    { drawable: 77, dlc: null },
    { drawable: 78, dlc: null, collection: null, overlay: null },
    { drawable: 79, dlc: null, collection: null, overlay: null },
    { drawable: 80, dlc: null, collection: null, overlay: null },
    { drawable: 0, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 1, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 2, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 3, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 4, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 5, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 6, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 7, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 8, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 9, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 10, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 11, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 12, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 13, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 14, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 15, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 16, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 17, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 18, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 19, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 20, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 21, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 22, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 23, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 24, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 25, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 26, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 27, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 28, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 29, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 30, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 31, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 32, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 33, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 34, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 35, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 36, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 37, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 38, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 39, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 40, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 41, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 42, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 43, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 44, dlc: 'mp_f_sgv', collection: null, overlay: null },
    { drawable: 45, dlc: 'mp_f_sgv', collection: null, overlay: null },
];

const maleHairOverlays = [
   { collection: null, overlay: null },
   { collection: 'mpbeach_overlays', overlay: 'FM_Hair_Fuzz' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_002' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_003' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_004' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_005' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_006' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_007' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_008' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_009' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_013' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_011' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_012' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_014' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_015' },
   { collection: 'multiplayer_overlays', overlay: 'NGBea_M_Hair_000' },
   { collection: 'multiplayer_overlays', overlay: 'NGBea_M_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NGBus_M_Hair_000' },
   { collection: 'multiplayer_overlays', overlay: 'NGBus_M_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NGHip_M_Hair_000' },
   { collection: 'multiplayer_overlays', overlay: 'NGHip_M_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NGInd_M_Hair_000' },
   { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_000' },
   { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_001' },
   { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_002' },
   { collection: 'mplowrider_overlays', overlay: 'LR_M_Hair_003' },
   { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_004' },
   { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_005' },
   { collection: 'mplowrider2_overlays', overlay: 'LR_M_Hair_006' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_000_M' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_001_M' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_002_M' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_003_M' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_004_M' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_005_M' },
   { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_M_000_M'},
   { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_M_001_M'},
   { collection: 'mpsecurity_overlays', overlay: 'MP_Security_Hair_001_M'},
];

const femaleHairOverlays = [
   { collection: null, overlay: null },
   { collection: 'mpbeach_overlays', overlay: 'FM_Hair_Fuzz' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_002' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_003' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_004' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_005' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_006' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_007' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_008' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_009' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_010' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_011' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_012' },
   { collection: 'multiplayer_overlays', overlay: 'NG_F_Hair_013' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_014' },
   { collection: 'multiplayer_overlays', overlay: 'NG_M_Hair_015' },
   { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_000' },
   { collection: 'multiplayer_overlays', overlay: 'NGBea_F_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NGBus_F_Hair_000' },
   { collection: 'multiplayer_overlays', overlay: 'NGBus_F_Hair_001' },
   { collection: 'multiplayer_overlays', overlay: 'NGHip_F_Hair_000' },
   { collection: 'multiplayer_overlays', overlay: 'NGInd_F_Hair_000' },
   { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_000' },
   { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_001' },
   { collection: 'mplowrider_overlays', overlay: 'LR_F_Hair_002' },
   { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_003' },
   { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_004' },
   { collection: 'mplowrider2_overlays', overlay: 'LR_F_Hair_006' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_000_F' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_001_F' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_002_F' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_003_F' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_006_F' },
   { collection: 'mpbiker_overlays', overlay: 'MP_Biker_Hair_004_F' },
   { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_F_000_F' },
   { collection: 'mpgunrunning_overlays', overlay: 'MP_Gunrunning_Hair_F_001_F' },
   { collection: 'mpsecurity_overlays', overlay: 'MP_Security_Hair_000_F'},
];