// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrevizaniRoleplay.Server;

#nullable disable

namespace TrevizaniRoleplay.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240321065102_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Animation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dictionary")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Flag")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("OnlyInVehicle")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Animations", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Banishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("StaffUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Banishments", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Blip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Color")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Blips", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnnouncementLastUseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Armor")
                        .HasColumnType("integer");

                    b.Property<int>("Badge")
                        .HasColumnType("integer");

                    b.Property<int>("Bank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("CKAvaliation")
                        .HasColumnType("boolean");

                    b.Property<int>("ConnectedTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeathReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DriverLicenseValidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DrugEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte?>("DrugItemCategory")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("EvaluatingStaffUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EvaluatorStaffUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExtraPayment")
                        .HasColumnType("integer");

                    b.Property<string>("FactionFlagsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FactionRankId")
                        .HasColumnType("uuid");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPLsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<DateTime?>("JailFinalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("Job")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("LastAccessHardwareIdExHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LastAccessHardwareIdHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LastAccessIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Mask")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("Model")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("NameChangeStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("PersonalizationJSON")
                        .HasColumnType("text");

                    b.Property<byte>("PersonalizationStep")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("PoliceOfficerBlockedDriverLicenseCharacterId")
                        .HasColumnType("uuid");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("RegisterHardwareIdExHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RegisterHardwareIdHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RegisterIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Savings")
                        .HasColumnType("integer");

                    b.Property<byte>("Sex")
                        .HasColumnType("smallint");

                    b.Property<byte>("ThresoldDeath")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ThresoldDeathEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Wound")
                        .HasColumnType("smallint");

                    b.Property<string>("WoundsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatingStaffUserId");

                    b.HasIndex("EvaluatorStaffUserId");

                    b.HasIndex("FactionId");

                    b.HasIndex("FactionRankId");

                    b.HasIndex("PoliceOfficerBlockedDriverLicenseCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharactersItems", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("BlipColor")
                        .HasColumnType("smallint");

                    b.Property<int>("BlipType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<DateTime?>("RentPaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("WeekRentValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CompanyCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlagsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompaniesCharacters", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Confiscation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PoliceOfficerCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.ToTable("Confiscations", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.ConfiscationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ConfiscationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConfiscationId");

                    b.ToTable("ConfiscationsItems", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CrackDen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CooldownDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CooldownHours")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownQuantityLimit")
                        .HasColumnType("integer");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<int>("OnlinePoliceOfficers")
                        .HasColumnType("integer");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CrackDens", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CrackDenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrackDenId")
                        .HasColumnType("uuid");

                    b.Property<byte>("ItemCategory")
                        .HasColumnType("smallint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CrackDenId");

                    b.ToTable("CrackDensItems", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CrackDenSell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrackDenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("ItemCategory")
                        .HasColumnType("smallint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CrackDenId");

                    b.ToTable("CrackDensSells", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Door", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<long>("Hash")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FactionId");

                    b.ToTable("Doors", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.EmergencyCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("EmergencyCalls", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatColor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Slots")
                        .HasColumnType("integer");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Factions", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Salary")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionsRanks", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionsStorages", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionStorageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.Property<Guid>("FactionStorageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FactionStorageId");

                    b.ToTable("FactionsStoragesItems", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionsUnits", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionUnitCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactionUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionUnitId");

                    b.ToTable("FactionsUnitsCharacters", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("FinancialTransactions", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Fine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PoliceOfficerCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.ToTable("Fines", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Furniture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Furnitures", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.HelpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffUserId");

                    b.HasIndex("UserId");

                    b.ToTable("HelpRequests", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Info", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Infos", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<float>("RotP")
                        .HasColumnType("real");

                    b.Property<float>("RotR")
                        .HasColumnType("real");

                    b.Property<float>("RotY")
                        .HasColumnType("real");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Jail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PoliceOfficerCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.ToTable("Jails", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginCharacterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OriginHardwareIdExHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OriginHardwareIdHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("OriginIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetHardwareIdExHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TargetHardwareIdHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("TargetIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OriginCharacterId");

                    b.HasIndex("TargetCharacterId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnnouncementValue")
                        .HasColumnType("integer");

                    b.Property<int>("BarberValue")
                        .HasColumnType("integer");

                    b.Property<bool>("Blackout")
                        .HasColumnType("boolean");

                    b.Property<int>("ClothesValue")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownDismantleHours")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownPropertyRobberyPropertyHours")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownPropertyRobberyRobberHours")
                        .HasColumnType("integer");

                    b.Property<int>("DriverLicenseBuyValue")
                        .HasColumnType("integer");

                    b.Property<int>("DriverLicenseRenewValue")
                        .HasColumnType("integer");

                    b.Property<byte>("EndTimeCrackDen")
                        .HasColumnType("smallint");

                    b.Property<int>("ExtraPaymentGarbagemanValue")
                        .HasColumnType("integer");

                    b.Property<int>("FirefightersBlockHeal")
                        .HasColumnType("integer");

                    b.Property<int>("FuelValue")
                        .HasColumnType("integer");

                    b.Property<int>("HospitalValue")
                        .HasColumnType("integer");

                    b.Property<string>("IPLsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InactivePropertiesDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("InitialTimeCrackDen")
                        .HasColumnType("smallint");

                    b.Property<int>("KeyValue")
                        .HasColumnType("integer");

                    b.Property<int>("LockValue")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCharactersOnline")
                        .HasColumnType("integer");

                    b.Property<int>("Paycheck")
                        .HasColumnType("integer");

                    b.Property<int>("PoliceOfficersPropertyRobbery")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyRobberyConnectedTime")
                        .HasColumnType("integer");

                    b.Property<int>("TattooValue")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleParkValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Prices", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntranceDimension")
                        .HasColumnType("integer");

                    b.Property<float>("EntrancePosX")
                        .HasColumnType("real");

                    b.Property<float>("EntrancePosY")
                        .HasColumnType("real");

                    b.Property<float>("EntrancePosZ")
                        .HasColumnType("real");

                    b.Property<float>("ExitPosX")
                        .HasColumnType("real");

                    b.Property<float>("ExitPosY")
                        .HasColumnType("real");

                    b.Property<float>("ExitPosZ")
                        .HasColumnType("real");

                    b.Property<byte>("Interior")
                        .HasColumnType("smallint");

                    b.Property<long>("LockNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<byte>("ProtectionLevel")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("RobberyCooldown")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RobberyValue")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.PropertyFurniture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Interior")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<float>("RotP")
                        .HasColumnType("real");

                    b.Property<float>("RotR")
                        .HasColumnType("real");

                    b.Property<float>("RotY")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertiesFurnitures", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.PropertyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<byte>("Slot")
                        .HasColumnType("smallint");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertiesItems", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Punishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("StaffUserId");

                    b.ToTable("Punishments", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrectQuestionAnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CorrectQuestionAnswerId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionsAnswers", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.SeizedVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PoliceOfficerCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.HasIndex("VehicleId");

                    b.ToTable("SeizedVehicles", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Spot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AuxiliarPosX")
                        .HasColumnType("real");

                    b.Property<float>("AuxiliarPosY")
                        .HasColumnType("real");

                    b.Property<float>("AuxiliarPosZ")
                        .HasColumnType("real");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Spots", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.TruckerLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedVehiclesJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryValue")
                        .HasColumnType("integer");

                    b.Property<int>("LoadWaitTime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<int>("UnloadWaitTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TruckerLocations", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.TruckerLocationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<Guid>("TruckerLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TruckerLocationId");

                    b.ToTable("TruckerLocationsDeliveries", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnnouncementToggle")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnsweredQuestions")
                        .HasColumnType("boolean");

                    b.Property<int>("CharacterApplicationsQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ChatFontSize")
                        .HasColumnType("integer");

                    b.Property<int>("ChatFontType")
                        .HasColumnType("integer");

                    b.Property<int>("ChatLines")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CooldownDismantle")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DiscordDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiscordUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("FactionChatToggle")
                        .HasColumnType("boolean");

                    b.Property<bool>("FactionToggle")
                        .HasColumnType("boolean");

                    b.Property<int>("ForumNameChanges")
                        .HasColumnType("integer");

                    b.Property<int>("HelpRequestsAnswersQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("LastAccessHardwareIdExHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LastAccessHardwareIdHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LastAccessIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NameChanges")
                        .HasColumnType("integer");

                    b.Property<bool>("PMToggle")
                        .HasColumnType("boolean");

                    b.Property<int>("PlateChanges")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PropertyRobberyCooldown")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("RegisterHardwareIdExHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RegisterHardwareIdHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RegisterIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("Staff")
                        .HasColumnType("smallint");

                    b.Property<bool>("StaffChatToggle")
                        .HasColumnType("boolean");

                    b.Property<int>("StaffDutyTime")
                        .HasColumnType("integer");

                    b.Property<string>("StaffFlagsJSON")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TimeStampToggle")
                        .HasColumnType("boolean");

                    b.Property<byte>("VIP")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("VIPValidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("VehicleTagToggle")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BodyAdditionalHealth")
                        .HasColumnType("bigint");

                    b.Property<long>("BodyHealth")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Color1B")
                        .HasColumnType("smallint");

                    b.Property<byte>("Color1G")
                        .HasColumnType("smallint");

                    b.Property<byte>("Color1R")
                        .HasColumnType("smallint");

                    b.Property<byte>("Color2B")
                        .HasColumnType("smallint");

                    b.Property<byte>("Color2G")
                        .HasColumnType("smallint");

                    b.Property<byte>("Color2R")
                        .HasColumnType("smallint");

                    b.Property<string>("DamagesJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DismantledValue")
                        .HasColumnType("integer");

                    b.Property<int>("EngineHealth")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fuel")
                        .HasColumnType("integer");

                    b.Property<byte>("HeadlightColor")
                        .HasColumnType("smallint");

                    b.Property<byte>("Job")
                        .HasColumnType("smallint");

                    b.Property<float>("LightsMultiplier")
                        .HasColumnType("real");

                    b.Property<byte>("Livery")
                        .HasColumnType("smallint");

                    b.Property<long>("LockNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ModsJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NeonBack")
                        .HasColumnType("boolean");

                    b.Property<byte>("NeonColorB")
                        .HasColumnType("smallint");

                    b.Property<byte>("NeonColorG")
                        .HasColumnType("smallint");

                    b.Property<byte>("NeonColorR")
                        .HasColumnType("smallint");

                    b.Property<bool>("NeonFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("NeonLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("NeonRight")
                        .HasColumnType("boolean");

                    b.Property<bool>("Parked")
                        .HasColumnType("boolean");

                    b.Property<int>("PetrolTankHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<byte>("ProtectionLevel")
                        .HasColumnType("smallint");

                    b.Property<float>("RotP")
                        .HasColumnType("real");

                    b.Property<float>("RotR")
                        .HasColumnType("real");

                    b.Property<float>("RotY")
                        .HasColumnType("real");

                    b.Property<int>("SeizedValue")
                        .HasColumnType("integer");

                    b.Property<bool>("Sold")
                        .HasColumnType("boolean");

                    b.Property<bool>("StaffGift")
                        .HasColumnType("boolean");

                    b.Property<string>("StructureDamagesJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("TireSmokeColorB")
                        .HasColumnType("smallint");

                    b.Property<byte>("TireSmokeColorG")
                        .HasColumnType("smallint");

                    b.Property<byte>("TireSmokeColorR")
                        .HasColumnType("smallint");

                    b.Property<byte>("WheelColor")
                        .HasColumnType("smallint");

                    b.Property<byte>("WheelType")
                        .HasColumnType("smallint");

                    b.Property<byte>("WheelVariation")
                        .HasColumnType("smallint");

                    b.Property<byte>("WindowTint")
                        .HasColumnType("smallint");

                    b.Property<bool>("XMR")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.VehicleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<byte>("Slot")
                        .HasColumnType("smallint");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehiclesItems", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Wanted", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PoliceOfficerCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PoliceOfficerDeletedCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("WantedCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WantedVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.HasIndex("PoliceOfficerDeletedCharacterId");

                    b.HasIndex("WantedCharacterId");

                    b.HasIndex("WantedVehicleId");

                    b.ToTable("Wanted", (string)null);
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Banishment", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");

                    b.Navigation("StaffUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Character", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "EvaluatingStaffUser")
                        .WithMany()
                        .HasForeignKey("EvaluatingStaffUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "EvaluatorStaffUser")
                        .WithMany()
                        .HasForeignKey("EvaluatorStaffUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.FactionRank", "FactionRank")
                        .WithMany()
                        .HasForeignKey("FactionRankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerBlockedDriverLicenseCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerBlockedDriverLicenseCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluatingStaffUser");

                    b.Navigation("EvaluatorStaffUser");

                    b.Navigation("Faction");

                    b.Navigation("FactionRank");

                    b.Navigation("PoliceOfficerBlockedDriverLicenseCharacter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CompanyCharacter", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Company", "Company")
                        .WithMany("Characters")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Confiscation", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Faction");

                    b.Navigation("PoliceOfficerCharacter");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.ConfiscationItem", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Confiscation", "Confiscation")
                        .WithMany("Items")
                        .HasForeignKey("ConfiscationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Confiscation");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CrackDenItem", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.CrackDen", "CrackDen")
                        .WithMany()
                        .HasForeignKey("CrackDenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrackDen");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.CrackDenSell", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.CrackDen", "CrackDen")
                        .WithMany()
                        .HasForeignKey("CrackDenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CrackDen");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Door", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionRank", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionStorage", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionStorageItem", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.FactionStorage", "FactionStorage")
                        .WithMany()
                        .HasForeignKey("FactionStorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactionStorage");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionUnit", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionUnitCharacter", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.FactionUnit", "FactionUnit")
                        .WithMany("Characters")
                        .HasForeignKey("FactionUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("FactionUnit");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Fine", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("PoliceOfficerCharacter");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.HelpRequest", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StaffUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Info", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Jail", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Faction");

                    b.Navigation("PoliceOfficerCharacter");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Log", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "OriginCharacter")
                        .WithMany()
                        .HasForeignKey("OriginCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OriginCharacter");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Property", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.PropertyFurniture", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Property", "Property")
                        .WithMany("Furnitures")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.PropertyItem", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Property", "Property")
                        .WithMany("Items")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Punishment", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Question", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.QuestionAnswer", "CorrectQuestionAnswer")
                        .WithMany()
                        .HasForeignKey("CorrectQuestionAnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrectQuestionAnswer");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.SeizedVehicle", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("PoliceOfficerCharacter");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Session", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.TruckerLocationDelivery", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.TruckerLocation", "TruckerLocation")
                        .WithMany()
                        .HasForeignKey("TruckerLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TruckerLocation");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.VehicleItem", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Items")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Wanted", b =>
                {
                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "PoliceOfficerDeletedCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerDeletedCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Character", "WantedCharacter")
                        .WithMany()
                        .HasForeignKey("WantedCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrevizaniRoleplay.Domain.Entities.Vehicle", "WantedVehicle")
                        .WithMany()
                        .HasForeignKey("WantedVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PoliceOfficerCharacter");

                    b.Navigation("PoliceOfficerDeletedCharacter");

                    b.Navigation("WantedCharacter");

                    b.Navigation("WantedVehicle");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Company", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Confiscation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.FactionUnit", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Property", b =>
                {
                    b.Navigation("Furnitures");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("TrevizaniRoleplay.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
