// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roleplay;

#nullable disable

namespace Roleplay.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Roleplay.Entities.Animation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Dictionary")
                        .HasColumnType("longtext");

                    b.Property<string>("Display")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Vehicle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Animations");
                });

            modelBuilder.Entity("Roleplay.Entities.Banishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("StaffUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("StaffUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Banishments");
                });

            modelBuilder.Entity("Roleplay.Entities.Blip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("Color")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Blips");
                });

            modelBuilder.Entity("Roleplay.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnnouncementLastUseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("Armor")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<int>("Bank")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CKAvaliation")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ConnectedTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeathReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DriverLicenseValidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DrugEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte?>("DrugItemCategory")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("EvaluatingStaffUserId")
                        .HasColumnType("int");

                    b.Property<int?>("EvaluatorStaffUserId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraPayment")
                        .HasColumnType("int");

                    b.Property<string>("FactionFlagsJSON")
                        .HasColumnType("longtext");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<int?>("FactionRankId")
                        .HasColumnType("int");

                    b.Property<ushort>("Health")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("History")
                        .HasColumnType("longtext");

                    b.Property<string>("IPLsJSON")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("JailFinalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Job")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("LastAccessHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("LastAccessHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LastAccessIp")
                        .HasColumnType("longtext");

                    b.Property<ulong>("Mask")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Model")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("NameChangeStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("PersonalizationJSON")
                        .HasColumnType("longtext");

                    b.Property<byte>("PersonalizationStep")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("PoliceOfficerBlockedDriverLicenseCharacterId")
                        .HasColumnType("int");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("RegisterHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RegisterHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("RegisterIp")
                        .HasColumnType("longtext");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<int>("Savings")
                        .HasColumnType("int");

                    b.Property<byte>("Sex")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("ThresoldDeath")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("ThresoldDeathEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte>("Wound")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("WoundsJSON")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatingStaffUserId");

                    b.HasIndex("EvaluatorStaffUserId");

                    b.HasIndex("FactionRankId");

                    b.HasIndex("PoliceOfficerBlockedDriverLicenseCharacterId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Roleplay.Entities.CharacterItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Extra")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("CharactersItems");
                });

            modelBuilder.Entity("Roleplay.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("BlipColor")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort>("BlipType")
                        .HasColumnType("smallint unsigned");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<DateTime?>("RentPaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WeekRentValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Roleplay.Entities.CompanyCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FlagsJSON")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompaniesCharacters");
                });

            modelBuilder.Entity("Roleplay.Entities.Confiscation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliceOfficerCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.ToTable("Confiscations");
                });

            modelBuilder.Entity("Roleplay.Entities.ConfiscationItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("ConfiscationId")
                        .HasColumnType("int");

                    b.Property<string>("Extra")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ConfiscationId");

                    b.ToTable("ConfiscationsItems");
                });

            modelBuilder.Entity("Roleplay.Entities.CrackDen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CooldownDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CooldownHours")
                        .HasColumnType("int");

                    b.Property<int>("CooldownQuantityLimit")
                        .HasColumnType("int");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<int>("OnlinePoliceOfficers")
                        .HasColumnType("int");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrackDens");
                });

            modelBuilder.Entity("Roleplay.Entities.CrackDenItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CrackDenId")
                        .HasColumnType("int");

                    b.Property<byte>("ItemCategory")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrackDensItems");
                });

            modelBuilder.Entity("Roleplay.Entities.CrackDenSell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CrackDenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("ItemCategory")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CrackDensSells");
                });

            modelBuilder.Entity("Roleplay.Entities.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<long>("Hash")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("Roleplay.Entities.EmergencyCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<uint>("Number")
                        .HasColumnType("int unsigned");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("EmergencyCalls");
                });

            modelBuilder.Entity("Roleplay.Entities.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ChatColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionArmory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FactionsArmories");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionArmoryWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ammo")
                        .HasColumnType("int");

                    b.Property<string>("ComponentsJSON")
                        .HasColumnType("longtext");

                    b.Property<int>("FactionArmoryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte>("TintIndex")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("Weapon")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("FactionsArmoriesWeapons");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionDrugHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FactionsDrugsHouses");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionDrugHouseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FactionDrugHouseId")
                        .HasColumnType("int");

                    b.Property<byte>("ItemCategory")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FactionsDrugsHousesItems");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FactionsRanks");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Plate")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("FactionsUnits");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionUnitCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("FactionUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionUnitId");

                    b.ToTable("FactionsUnitsCharacters");
                });

            modelBuilder.Entity("Roleplay.Entities.FinancialTransaction", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("Roleplay.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PoliceOfficerCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("Roleplay.Entities.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("Roleplay.Entities.HelpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("StaffUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HelpRequests");
                });

            modelBuilder.Entity("Roleplay.Entities.Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("Roleplay.Entities.Item", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<string>("Extra")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("RotP")
                        .HasColumnType("float");

                    b.Property<float>("RotR")
                        .HasColumnType("float");

                    b.Property<float>("RotY")
                        .HasColumnType("float");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Roleplay.Entities.Jail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliceOfficerCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.ToTable("Jails");
                });

            modelBuilder.Entity("Roleplay.Entities.Log", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("OriginCharacterId")
                        .HasColumnType("int");

                    b.Property<ulong>("OriginHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("OriginHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("OriginIp")
                        .HasColumnType("longtext");

                    b.Property<int?>("TargetCharacterId")
                        .HasColumnType("int");

                    b.Property<ulong>("TargetHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("TargetHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TargetIp")
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("OriginCharacterId");

                    b.HasIndex("TargetCharacterId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Roleplay.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnnouncementValue")
                        .HasColumnType("int");

                    b.Property<int>("BarberValue")
                        .HasColumnType("int");

                    b.Property<bool>("Blackout")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClothesValue")
                        .HasColumnType("int");

                    b.Property<int>("CooldownDismantleHours")
                        .HasColumnType("int");

                    b.Property<int>("CooldownPropertyRobberyPropertyHours")
                        .HasColumnType("int");

                    b.Property<int>("CooldownPropertyRobberyRobberHours")
                        .HasColumnType("int");

                    b.Property<int>("DriverLicenseBuyValue")
                        .HasColumnType("int");

                    b.Property<int>("DriverLicenseRenewValue")
                        .HasColumnType("int");

                    b.Property<byte>("EndTimeCrackDen")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("ExtraPaymentGarbagemanValue")
                        .HasColumnType("int");

                    b.Property<int>("FirefightersBlockHeal")
                        .HasColumnType("int");

                    b.Property<int>("FuelValue")
                        .HasColumnType("int");

                    b.Property<int>("HospitalValue")
                        .HasColumnType("int");

                    b.Property<string>("IPLsJSON")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("InactivePropertiesDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("InitialTimeCrackDen")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("KeyValue")
                        .HasColumnType("int");

                    b.Property<int>("LockValue")
                        .HasColumnType("int");

                    b.Property<int>("MaxCharactersOnline")
                        .HasColumnType("int");

                    b.Property<int>("Paycheck")
                        .HasColumnType("int");

                    b.Property<int>("PoliceOfficersPropertyRobbery")
                        .HasColumnType("int");

                    b.Property<int>("PropertyRobberyConnectedTime")
                        .HasColumnType("int");

                    b.Property<int>("TattooValue")
                        .HasColumnType("int");

                    b.Property<int>("VehicleParkValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Roleplay.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<float>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Roleplay.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<float>("EntrancePosX")
                        .HasColumnType("float");

                    b.Property<float>("EntrancePosY")
                        .HasColumnType("float");

                    b.Property<float>("EntrancePosZ")
                        .HasColumnType("float");

                    b.Property<float>("ExitPosX")
                        .HasColumnType("float");

                    b.Property<float>("ExitPosY")
                        .HasColumnType("float");

                    b.Property<float>("ExitPosZ")
                        .HasColumnType("float");

                    b.Property<byte>("Interior")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("LockNumber")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("ProtectionLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("RobberyCooldown")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RobberyValue")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Roleplay.Entities.PropertyFurniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Interior")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<float>("RotP")
                        .HasColumnType("float");

                    b.Property<float>("RotR")
                        .HasColumnType("float");

                    b.Property<float>("RotY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertiesFurnitures");
                });

            modelBuilder.Entity("Roleplay.Entities.PropertyItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Extra")
                        .HasColumnType("longtext");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("PropertiesItems");
                });

            modelBuilder.Entity("Roleplay.Entities.Punishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("StaffUserId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("StaffUserId");

                    b.ToTable("Punishments");
                });

            modelBuilder.Entity("Roleplay.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CorrectQuestionAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Roleplay.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuestionsAnswers");
                });

            modelBuilder.Entity("Roleplay.Entities.SeizedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PoliceOfficerCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeizedVehicles");
                });

            modelBuilder.Entity("Roleplay.Entities.Session", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Roleplay.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("AuxiliarPosX")
                        .HasColumnType("float");

                    b.Property<float>("AuxiliarPosY")
                        .HasColumnType("float");

                    b.Property<float>("AuxiliarPosZ")
                        .HasColumnType("float");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Spots");
                });

            modelBuilder.Entity("Roleplay.Entities.TruckerLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllowedVehiclesJSON")
                        .HasColumnType("longtext");

                    b.Property<int>("DeliveryValue")
                        .HasColumnType("int");

                    b.Property<int>("LoadWaitTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<int>("UnloadWaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TruckerLocations");
                });

            modelBuilder.Entity("Roleplay.Entities.TruckerLocationDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<int>("TruckerLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TruckerLocationsDeliveries");
                });

            modelBuilder.Entity("Roleplay.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AnnouncementToggle")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CharacterApplicationsQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ChatFontSize")
                        .HasColumnType("int");

                    b.Property<int>("ChatFontType")
                        .HasColumnType("int");

                    b.Property<int>("ChatLines")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CooldownDismantle")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Discord")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("DiscordConfirmationToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("longtext");

                    b.Property<bool>("FactionChatToggle")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FactionToggle")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ForumNameChanges")
                        .HasColumnType("int");

                    b.Property<int>("HelpRequestsAnswersQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("LastAccessHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("LastAccessHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LastAccessIp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("NameChanges")
                        .HasColumnType("int");

                    b.Property<bool>("PMToggle")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("PlateChanges")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PropertyRobberyCooldown")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("RegisterHardwareIdExHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RegisterHardwareIdHash")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("RegisterIp")
                        .HasColumnType("longtext");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<int>("Staff")
                        .HasColumnType("int");

                    b.Property<bool>("StaffChatToggle")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StaffDutyTime")
                        .HasColumnType("int");

                    b.Property<string>("StaffFlagsJSON")
                        .HasColumnType("longtext");

                    b.Property<bool>("TimeStampToggle")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("VIP")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("VIPValidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("VehicleTagToggle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Roleplay.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint>("BodyAdditionalHealth")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BodyHealth")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<byte>("Color1B")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Color1G")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Color1R")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Color2B")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Color2G")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Color2R")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("DamagesJSON")
                        .HasColumnType("longtext");

                    b.Property<int>("DismantledValue")
                        .HasColumnType("int");

                    b.Property<int>("EngineHealth")
                        .HasColumnType("int");

                    b.Property<bool>("FactionGift")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<byte>("HeadlightColor")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Job")
                        .HasColumnType("tinyint unsigned");

                    b.Property<float>("LightsMultiplier")
                        .HasColumnType("float");

                    b.Property<byte>("Livery")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("LockNumber")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("ModsJSON")
                        .HasColumnType("longtext");

                    b.Property<bool>("NeonBack")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("NeonColorB")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("NeonColorG")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("NeonColorR")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("NeonFront")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NeonLeft")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NeonRight")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Parked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PetrolTankHealth")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .HasColumnType("longtext");

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.Property<byte>("ProtectionLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<float>("RotP")
                        .HasColumnType("float");

                    b.Property<float>("RotR")
                        .HasColumnType("float");

                    b.Property<float>("RotY")
                        .HasColumnType("float");

                    b.Property<int>("SeizedValue")
                        .HasColumnType("int");

                    b.Property<bool>("Sold")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StructureDamagesJSON")
                        .HasColumnType("longtext");

                    b.Property<byte>("TireSmokeColorB")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("TireSmokeColorG")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("TireSmokeColorR")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WheelColor")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WheelType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WheelVariation")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WindowTint")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("XMR")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Roleplay.Entities.VehicleItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Extra")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehiclesItems");
                });

            modelBuilder.Entity("Roleplay.Entities.Wanted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PoliceOfficerCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("PoliceOfficerDeletedCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int?>("WantedCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("WantedVehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliceOfficerCharacterId");

                    b.HasIndex("WantedCharacterId");

                    b.HasIndex("WantedVehicleId");

                    b.ToTable("Wanted");
                });

            modelBuilder.Entity("Roleplay.Entities.Banishment", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Character");

                    b.Navigation("StaffUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roleplay.Entities.Character", b =>
                {
                    b.HasOne("Roleplay.Entities.User", "EvaluatingStaffUser")
                        .WithMany("EvaluatingCharacters")
                        .HasForeignKey("EvaluatingStaffUserId");

                    b.HasOne("Roleplay.Entities.User", "EvaluatorStaffUser")
                        .WithMany("EvaluatorCharacters")
                        .HasForeignKey("EvaluatorStaffUserId");

                    b.HasOne("Roleplay.Entities.FactionRank", "FactionRank")
                        .WithMany()
                        .HasForeignKey("FactionRankId");

                    b.HasOne("Roleplay.Entities.Character", "PoliceOfficerBlockedDriverLicenseCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerBlockedDriverLicenseCharacterId");

                    b.HasOne("Roleplay.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluatingStaffUser");

                    b.Navigation("EvaluatorStaffUser");

                    b.Navigation("FactionRank");

                    b.Navigation("PoliceOfficerBlockedDriverLicenseCharacter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roleplay.Entities.CompanyCharacter", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Company", "Company")
                        .WithMany("Characters")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Roleplay.Entities.Confiscation", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Faction");

                    b.Navigation("PoliceOfficerCharacter");
                });

            modelBuilder.Entity("Roleplay.Entities.ConfiscationItem", b =>
                {
                    b.HasOne("Roleplay.Entities.Confiscation", "Confiscation")
                        .WithMany("Items")
                        .HasForeignKey("ConfiscationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confiscation");
                });

            modelBuilder.Entity("Roleplay.Entities.CrackDenSell", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionUnit", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionUnitCharacter", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.FactionUnit", "FactionUnit")
                        .WithMany("Characters")
                        .HasForeignKey("FactionUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("FactionUnit");
                });

            modelBuilder.Entity("Roleplay.Entities.Fine", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("PoliceOfficerCharacter");
                });

            modelBuilder.Entity("Roleplay.Entities.Info", b =>
                {
                    b.HasOne("Roleplay.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roleplay.Entities.Jail", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Faction");

                    b.Navigation("PoliceOfficerCharacter");
                });

            modelBuilder.Entity("Roleplay.Entities.Log", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "OriginCharacter")
                        .WithMany()
                        .HasForeignKey("OriginCharacterId");

                    b.HasOne("Roleplay.Entities.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId");

                    b.Navigation("OriginCharacter");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("Roleplay.Entities.Property", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Roleplay.Entities.PropertyFurniture", b =>
                {
                    b.HasOne("Roleplay.Entities.Property", "Property")
                        .WithMany("Furnitures")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Roleplay.Entities.Punishment", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("Roleplay.Entities.Vehicle", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("Roleplay.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId");

                    b.Navigation("Character");

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("Roleplay.Entities.Wanted", b =>
                {
                    b.HasOne("Roleplay.Entities.Character", "PoliceOfficerCharacter")
                        .WithMany()
                        .HasForeignKey("PoliceOfficerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roleplay.Entities.Character", "WantedCharacter")
                        .WithMany()
                        .HasForeignKey("WantedCharacterId");

                    b.HasOne("Roleplay.Entities.Vehicle", "WantedVehicle")
                        .WithMany()
                        .HasForeignKey("WantedVehicleId");

                    b.Navigation("PoliceOfficerCharacter");

                    b.Navigation("WantedCharacter");

                    b.Navigation("WantedVehicle");
                });

            modelBuilder.Entity("Roleplay.Entities.Company", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Roleplay.Entities.Confiscation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Roleplay.Entities.FactionUnit", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Roleplay.Entities.Property", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Roleplay.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("EvaluatingCharacters");

                    b.Navigation("EvaluatorCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
