announcementDiscordChannel = 1218597555584368640
companyAnnouncementDiscordChannel = 1218597579516936213
dbConnectionString = 'Host=localhost;Port=5432;Database=trevizaniroleplay;User ID=postgres;Password=159357;Pooling=true;'
debug = true
discordBotToken = ''
gamemode = 'Roleplay'
governmentAnnouncementDiscordChannel = 1218597600161435779
language = 'pt'
modules = ['csharp-module', 'js-module']
name = 'Trevizani Roleplay'
players = 200
port = 7788
resources = ['client', 'server']
rolesStaffMessage = [1218597330882920551]
staffDiscordChannel = 1218597502073311372
tags = ['text']
website = 'trevizani.com.br'
